// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";

/**
 * Definição estática de um building.
 */
export type BuildingDef = { id: BuildingId, name: string, ascii_icon: string, description: string, base_cost: number, cost_growth: number, 
/**
 * Produção por unidade por segundo.
 */
base_production: number, unlock_cost: number, 
/**
 * Era mínima pra aparecer na shop.
 */
era_required: number, flavor_text: string, };
