// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum tipado dos 10 buildings. Serializa como snake_case string pro frontend.
 */
export type BuildingId = "if_else_bot" | "markov_chain" | "rnn" | "lstm" | "transformer" | "gpt_like" | "multimodal" | "agi" | "asi" | "quantum";
