// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De onde vem o diálogo do modelo nessa era.
 */
export type ChatSource = "hardcoded" | "nano_model" | "claude_api";
