// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tipo de efeito. Separar os tipos permite lookup O(1) no ResourceManager.
 */
export type EffectKind = "tokens_mult" | "compute_mult" | "data_mult" | "hype_gain" | "hallucination_reduction" | "funding_mult";
