// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSource } from "./ChatSource";
import type { EraId } from "./EraId";

export type EraDef = { id: EraId, name: string, title: string, description: string, 
/**
 * `total_tokens_earned` mínimo pra avançar.
 */
unlock_threshold: number, production_multiplier: number, chat_source: ChatSource, chat_style: string, };
