// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Era IDs tipados — preservam ordem canônica.
 */
export type EraId = "Hardcoded" | "Statistical" | "Neural" | "Transformer" | "Foundation" | "Emergent" | "Singularity" | "Transcendent";
