// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EraId } from "./EraId";
import type { Resources } from "./Resources";

/**
 * Estado completo de um jogador. Única source of truth.
 *
 * **Invariante**: todos os campos devem existir em `GAME_CONCEPT.md` e
 * ter a mesma semântica. Campos novos requerem bump de `SAVE_VERSION`.
 */
export type GameState = { version: number, player_id: string, display_name: string, 
/**
 * Timestamps em ms epoch.
 */
created_at: bigint, last_tick: bigint, tick_count: bigint, resources: Resources, total_tokens_earned: number, 
/**
 * Mapa building → quantidade. String key pra JSON-friendly.
 */
buildings: { [key in string]?: number }, 
/**
 * IDs de upgrades comprados (one-shot).
 */
upgrades: Array<string>, era: EraId, prestige_count: number, insight_points: number, 
/**
 * Array com stacks (IDs podem repetir).
 */
permanent_upgrades: Array<string>, reborn_count: number, reborn_points: number, unlocked_perks: Array<string>, total_prestiges_all_time: number, 
/**
 * Sincronizado com o Python `/evaluate`.
 */
ml_steps_trained: number, ml_capability_score: bigint, achievements: Array<string>, };
