// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerkEffect = "start_ip" | "neural_mult" | "era_discount" | "compound_prestige" | "auto_click" | "second_wind" | "offline_master" | "oracle" | "click_multi" | "cheaper_buildings";
