// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerkEffect } from "./PerkEffect";

export type PerkDef = { id: string, name: string, description: string, cost: number, effect: PerkEffect, value: number, max_stacks: number | null, flavor: string, };
