// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermanentEffect } from "./PermanentEffect";

export type PermanentUpgradeDef = { id: string, name: string, description: string, cost: number, effect: PermanentEffect, value: number, max_stacks: number | null, flavor: string, };
