// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermanentEffect = "start_tokens" | "production_mult" | "offline_efficiency" | "hallucination_base" | "cheaper_upgrades" | "starting_building";
