// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seis recursos interligados. Ver `GAME_CONCEPT.md` para a dinâmica.
 */
export type Resources = { tokens: number, compute: number, data: number, funding: number, hype: number, 
/**
 * 0.0–1.0. Em 1.0, drena 100% da produção e dispara "rogue" event.
 */
hallucinations: number, };
