// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectKind } from "./EffectKind";

export type UpgradeEffect = { kind: EffectKind, value: number, };
