// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostResource } from "./CostResource";
import type { UpgradeCategory } from "./UpgradeCategory";
import type { UpgradeEffect } from "./UpgradeEffect";

export type UpgradeDef = { id: string, name: string, description: string, category: UpgradeCategory, cost: number, cost_resource: CostResource, era_required: number, effects: Array<UpgradeEffect>, flavor: string, };
